---
language: python
python: "3.8"
dist: focal
sudo: required
addons:
  apt:
    sources:
      - docker: "deb https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
services:
  - docker
env:
  - SITE=test.yml

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -o Dpkg::Options::="--force-confold" --force-yes -y docker-ce

install:
  # Install Ansible.
  - pip install ansible==2.9.13
  - pip install ansible-lint
  - pip install molecule
  - pip install docker

script:
  - echo "Tests bypass"
  # - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
