---
dependency:
  name: galaxy
driver:
  name: docker
  provider:
    name: virtualbox
lint: |
  ansible-lint
platforms:
  - name: instance
    image: ubuntu:20.04
    box: bento/ubuntu-20.04
    memory: 1024
    cpus: 1
    privileged: true
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
